<a href="https://colab.research.google.com/github/jamesodukoya/WebScraping/blob/main/Web_Scraping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Scraping Table Data from Wikipedia

##Importing Beautiful Soup Library

In [74]:
from bs4 import BeautifulSoup
import requests

In [75]:
url = "https://en.wikipedia.org/wiki/List_of_largest_companies_in_the_United_States_by_revenue"

page = requests.get(url)

content = BeautifulSoup(page.text, 'html')

table=content.find_all('table')[1]

In [76]:
titles=table.find_all('th')
titles=[heading.text.strip() for heading in titles]

##Importing Pandas and Creating Table

In [77]:
import pandas as pd
frame=pd.DataFrame(columns=titles)

##Getting Data from Each Table Row and Adding It to Our Table

In [78]:
column_data=table.find_all('tr')

In [79]:
for row in column_data[1:]:
  row_data=row.find_all('td')
  individual_row_data=[data.text.strip() for data in row_data]
  length=len(frame)
  frame.loc[length]=individual_row_data
frame

,Rank,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
0,1,Walmart,Retail,"611,289",6.7%,"2,100,000","Bentonville, Arkansas"
1,2,Amazon,Retail and cloud computing,"513,983",9.4%,"1,540,000","Seattle, Washington"
2,3,ExxonMobil,Petroleum industry,"413,680",44.8%,"62,000","Spring, Texas"
3,4,Apple,Electronics industry,"394,328",7.8%,"164,000","Cupertino, California"
4,5,UnitedHealth Group,Healthcare,"324,162",12.7%,"400,000","Minnetonka, Minnesota"
...,...,...,...,...,...,...,...
95,96,Best Buy,Retail,"46,298",10.6%,"71,100","Richfield, Minnesota"
96,97,Bristol-Myers Squibb,Pharmaceutical industry,"46,159",0.5%,"34,300","New York City, New York"
97,98,United Airlines,Airline,"44,955",82.5%,"92,795","Chicago, Illinois"
98,99,Thermo Fisher Scientific,Laboratory instruments,"44,915",14.5%,"130,000","Waltham, Massachusetts"
99,100,Qualcomm,Technology,"44,200",31.7%,"51,000","San Diego, California"

##Exporting Table to Local CSV file

In [80]:
frame.to_csv(r'C:\Users\oduko\Downloads\Companies.csv', index=False)